# Generated by Django 3.2.9 on 2021-12-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20211204_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/d/'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
