"""empty message

Revision ID: c9efee297434
Revises: b9ddc9073fa8
Create Date: 2021-12-23 13:04:41.027811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9efee297434'
down_revision = 'b9ddc9073fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('interviews', 'start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('interviews', 'start_time')
    # ### end Alembic commands ###
